### ISSUE TITLE
I can't use to Home Assistant0.90.2

### ISSUE THREAD

**Issue by Kanson4** [abelectronicsuk/abelectronics-home-assistant-custom-components#2]
I follow WIKI and I get an error message: Unable to find platform iopiswitch.

Then I put iopiswitch.py in the /custom_components directory. Got the following error message:
Unable to find platform iopiswitch. Search path was limited to path of component: custom_components
2:27 loader.py (ERROR)
Error loading custom_components.iopiswitch.switch. Make sure all dependencies are installed
2:27 loader.py (ERROR)
You are using a custom component for iopiswitch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2:27 loader.py (WARNING)

thanks
Kanson

**Comment by abelectronicsuk** [comment]
Hello Kanson

It appears that our add-on no longer works with Home Assistant after version 0.88 due to changes in the way add-ons function.

I have found another add-on for the MCP23017 that may work with the current version of Home Assistant, you can download it from [https://github.com/jardiamj/homeassistant/tree/master/custom_components ](https://github.com/jardiamj/homeassistant/tree/master/custom_components )
